{
  "id": "USN-5888-1",
  "summary": "python3.9 vulnerabilities",
  "details": "It was discovered that Python incorrectly handled certain inputs. If a\nuser or an automated system were tricked into opening a specially\ncrafted input file, a remote attacker could possibly use this issue to\nexecute arbitrary code. (CVE-2015-20107)\n\nHamza Avvan discovered that Python incorrectly handled certain inputs. If a\nuser or an automated system were tricked into running a specially\ncrafted input, a remote attacker could possibly use this issue to execute\narbitrary code. (CVE-2021-28861)\n\nIt was discovered that Python incorrectly handled certain inputs. If a\nuser or an automated system were tricked into running a specially\ncrafted input, a remote attacker could possibly use this issue to execute\narbitrary code. (CVE-2022-37454, CVE-2022-42919)\n\nIt was discovered that Python incorrectly handled certain inputs. If a\nuser or an automated system were tricked into running a specially\ncrafted input, a remote attacker could possibly use this issue to cause a\ndenial of service. (CVE-2022-45061, CVE-2023-24329)\n",
  "aliases": [],
  "related": [
    "CVE-2015-20107",
    "CVE-2021-28861",
    "CVE-2022-37454",
    "CVE-2022-42919",
    "CVE-2022-45061",
    "CVE-2023-24329"
  ],
  "published": "2023-02-27T17:08:31.229248Z",
  "modified": "2023-02-27T17:08:31.229248Z",
  "affected": [
    {
      "package": {
        "ecosystem": "Ubuntu:20.04:LTS:Pro",
        "name": "python3.9"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "3.9.5-3ubuntu0~20.04.1+esm1"
            }
          ]
        }
      ],
      "ecosystem_specific": {
        "binaries": [
          {
            "python3.9-dev": "3.9.5-3ubuntu0~20.04.1+esm1",
            "python3.9-examples": "3.9.5-3ubuntu0~20.04.1+esm1",
            "libpython3.9-minimal": "3.9.5-3ubuntu0~20.04.1+esm1",
            "python3.9-full": "3.9.5-3ubuntu0~20.04.1+esm1",
            "python3.9-venv": "3.9.5-3ubuntu0~20.04.1+esm1",
            "python3.9-doc": "3.9.5-3ubuntu0~20.04.1+esm1",
            "libpython3.9-dev": "3.9.5-3ubuntu0~20.04.1+esm1",
            "libpython3.9": "3.9.5-3ubuntu0~20.04.1+esm1",
            "python3.9-minimal": "3.9.5-3ubuntu0~20.04.1+esm1",
            "idle-python3.9": "3.9.5-3ubuntu0~20.04.1+esm1",
            "libpython3.9-testsuite": "3.9.5-3ubuntu0~20.04.1+esm1",
            "libpython3.9-stdlib": "3.9.5-3ubuntu0~20.04.1+esm1",
            "python3.9": "3.9.5-3ubuntu0~20.04.1+esm1"
          }
        ],
        "availability": "Available with Ubuntu Pro: https://ubuntu.com/pro"
      }
    }
  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://ubuntu.com/security/notices/USN-5888-1"
    },
    {
      "type": "REPORT",
      "url": "https://ubuntu.com/security/CVE-2015-20107"
    },
    {
      "type": "REPORT",
      "url": "https://ubuntu.com/security/CVE-2021-28861"
    },
    {
      "type": "REPORT",
      "url": "https://ubuntu.com/security/CVE-2022-37454"
    },
    {
      "type": "REPORT",
      "url": "https://ubuntu.com/security/CVE-2022-42919"
    },
    {
      "type": "REPORT",
      "url": "https://ubuntu.com/security/CVE-2022-45061"
    },
    {
      "type": "REPORT",
      "url": "https://ubuntu.com/security/CVE-2023-24329"
    }
  ]
}