{
  "id": "USN-4668-1",
  "summary": "python-apt vulnerability",
  "details": "Kevin Backhouse discovered that python-apt incorrectly handled resources. A\nlocal attacker could possibly use this issue to cause python-apt to consume\nresources, leading to a denial of service.\n",
  "aliases": [],
  "related": [
    "CVE-2020-27351"
  ],
  "published": "2020-12-09T17:36:45.504991Z",
  "modified": "2020-12-09T17:36:45.504991Z",
  "affected": [
    {
      "package": {
        "ecosystem": "Ubuntu:20.04:LTS",
        "name": "python-apt"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "2.0.0ubuntu0.20.04.2"
            }
          ]
        }
      ],
      "ecosystem_specific": {
        "binaries": [
          {
            "python3-apt": "2.0.0ubuntu0.20.04.2",
            "python-apt": "2.0.0ubuntu0.20.04.2",
            "python-apt-common": "2.0.0ubuntu0.20.04.2",
            "python-apt-dev": "2.0.0ubuntu0.20.04.2",
            "python-apt-doc": "2.0.0ubuntu0.20.04.2"
          }
        ],
        "availability": "No subscription needed"
      }
    },
    {
      "package": {
        "ecosystem": "Ubuntu:18.04:LTS",
        "name": "python-apt"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "1.6.5ubuntu0.4"
            }
          ]
        }
      ],
      "ecosystem_specific": {
        "binaries": [
          {
            "python3-apt": "1.6.5ubuntu0.4",
            "python-apt": "1.6.5ubuntu0.4",
            "python-apt-common": "1.6.5ubuntu0.4",
            "python-apt-dev": "1.6.5ubuntu0.4",
            "python-apt-doc": "1.6.5ubuntu0.4"
          }
        ],
        "availability": "No subscription needed"
      }
    },
    {
      "package": {
        "ecosystem": "Ubuntu:16.04:LTS",
        "name": "python-apt"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "1.1.0~beta1ubuntu0.16.04.10"
            }
          ]
        }
      ],
      "ecosystem_specific": {
        "binaries": [
          {
            "python3-apt": "1.1.0~beta1ubuntu0.16.04.10",
            "python-apt": "1.1.0~beta1ubuntu0.16.04.10",
            "python-apt-common": "1.1.0~beta1ubuntu0.16.04.10",
            "python-apt-dev": "1.1.0~beta1ubuntu0.16.04.10",
            "python-apt-doc": "1.1.0~beta1ubuntu0.16.04.10"
          }
        ],
        "availability": "No subscription needed"
      }
    }
  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://ubuntu.com/security/notices/USN-4668-1"
    },
    {
      "type": "REPORT",
      "url": "https://ubuntu.com/security/CVE-2020-27351"
    }
  ]
}