{
  "id": "USN-5083-1",
  "summary": "python3.4, python3.5 vulnerabilities",
  "details": "It was discovered that Python incorrectly handled certain RFCs.\nAn attacker could possibly use this issue to cause a denial of service.\nThis issue only affected Ubuntu 16.04 ESM. (CVE-2021-3733)\n\nIt was discovered that Python incorrectly handled certain\nserver responses. An attacker could possibly use this issue to\ncause a denial of service. (CVE-2021-3737)\n",
  "aliases": [],
  "related": [
    "CVE-2021-3733",
    "CVE-2021-3737"
  ],
  "published": "2021-09-16T19:27:34.033368Z",
  "modified": "2021-09-16T19:27:34.033368Z",
  "affected": [
    {
      "package": {
        "ecosystem": "Ubuntu:14.04:LTS:Pro",
        "name": "python3.4"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "3.4.3-1ubuntu1~14.04.7+esm11"
            }
          ]
        }
      ],
      "ecosystem_specific": {
        "binaries": [
          {
            "python3.4-dev": "3.4.3-1ubuntu1~14.04.7+esm11",
            "libpython3.4-testsuite": "3.4.3-1ubuntu1~14.04.7+esm11",
            "libpython3.4-dev": "3.4.3-1ubuntu1~14.04.7+esm11",
            "python3.4-minimal": "3.4.3-1ubuntu1~14.04.7+esm11",
            "python3.4-venv": "3.4.3-1ubuntu1~14.04.7+esm11",
            "python3.4": "3.4.3-1ubuntu1~14.04.7+esm11",
            "python3.4-doc": "3.4.3-1ubuntu1~14.04.7+esm11",
            "idle-python3.4": "3.4.3-1ubuntu1~14.04.7+esm11",
            "libpython3.4-minimal": "3.4.3-1ubuntu1~14.04.7+esm11",
            "libpython3.4": "3.4.3-1ubuntu1~14.04.7+esm11",
            "python3.4-examples": "3.4.3-1ubuntu1~14.04.7+esm11",
            "libpython3.4-stdlib": "3.4.3-1ubuntu1~14.04.7+esm11"
          }
        ],
        "availability": "Available with Ubuntu Pro: https://ubuntu.com/pro"
      }
    },
    {
      "package": {
        "ecosystem": "Ubuntu:16.04:LTS:Pro",
        "name": "python3.5"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "3.5.2-2ubuntu0~16.04.13+esm1"
            }
          ]
        }
      ],
      "ecosystem_specific": {
        "binaries": [
          {
            "libpython3.5-stdlib": "3.5.2-2ubuntu0~16.04.13+esm1",
            "libpython3.5-minimal": "3.5.2-2ubuntu0~16.04.13+esm1",
            "python3.5-venv": "3.5.2-2ubuntu0~16.04.13+esm1",
            "python3.5": "3.5.2-2ubuntu0~16.04.13+esm1",
            "python3.5-minimal": "3.5.2-2ubuntu0~16.04.13+esm1",
            "python3.5-doc": "3.5.2-2ubuntu0~16.04.13+esm1",
            "libpython3.5-testsuite": "3.5.2-2ubuntu0~16.04.13+esm1",
            "libpython3.5": "3.5.2-2ubuntu0~16.04.13+esm1",
            "libpython3.5-dev": "3.5.2-2ubuntu0~16.04.13+esm1",
            "python3.5-examples": "3.5.2-2ubuntu0~16.04.13+esm1",
            "python3.5-dev": "3.5.2-2ubuntu0~16.04.13+esm1",
            "idle-python3.5": "3.5.2-2ubuntu0~16.04.13+esm1"
          }
        ],
        "availability": "Available with Ubuntu Pro: https://ubuntu.com/pro"
      }
    }
  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://ubuntu.com/security/notices/USN-5083-1"
    },
    {
      "type": "REPORT",
      "url": "https://ubuntu.com/security/CVE-2021-3733"
    },
    {
      "type": "REPORT",
      "url": "https://ubuntu.com/security/CVE-2021-3737"
    }
  ]
}