{
  "id": "USN-4888-1",
  "summary": "ldb vulnerabilities",
  "details": "Douglas Bagnall discovered that ldb, when used with Samba, incorrectly\nhandled certain LDAP attributes. A remote attacker could possibly use this\nissue to cause the LDAP server to crash, resulting in a denial of service.\n(CVE-2021-20277)\n\nDouglas Bagnall discovered that ldb, when used with Samba, incorrectly\nhandled certain DN strings. A remote attacker could use this issue to\ncause the LDAP server to crash, resulting in a denial of service, or\npossibly execute arbitrary code. (CVE-2020-27840)\n",
  "aliases": [],
  "related": [
    "CVE-2020-27840",
    "CVE-2021-20277"
  ],
  "published": "2021-03-24T18:08:35.244876Z",
  "modified": "2021-03-24T18:08:35.244876Z",
  "affected": [
    {
      "package": {
        "ecosystem": "Ubuntu:18.04:LTS",
        "name": "ldb"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "2:1.2.3-1ubuntu0.2"
            }
          ]
        }
      ],
      "ecosystem_specific": {
        "binaries": [
          {
            "ldb-tools": "2:1.2.3-1ubuntu0.2",
            "python-ldb-dev": "2:1.2.3-1ubuntu0.2",
            "python-ldb": "2:1.2.3-1ubuntu0.2",
            "libldb1": "2:1.2.3-1ubuntu0.2",
            "libldb-dev": "2:1.2.3-1ubuntu0.2"
          }
        ],
        "availability": "No subscription needed"
      }
    },
    {
      "package": {
        "ecosystem": "Ubuntu:20.04:LTS",
        "name": "ldb"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "2:2.0.10-0ubuntu0.20.04.3"
            }
          ]
        }
      ],
      "ecosystem_specific": {
        "binaries": [
          {
            "ldb-tools": "2:2.0.10-0ubuntu0.20.04.3",
            "libldb2": "2:2.0.10-0ubuntu0.20.04.3",
            "python3-ldb": "2:2.0.10-0ubuntu0.20.04.3",
            "libldb-dev": "2:2.0.10-0ubuntu0.20.04.3",
            "python3-ldb-dev": "2:2.0.10-0ubuntu0.20.04.3"
          }
        ],
        "availability": "No subscription needed"
      }
    },
    {
      "package": {
        "ecosystem": "Ubuntu:16.04:LTS",
        "name": "ldb"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "2:1.1.24-1ubuntu3.2"
            }
          ]
        }
      ],
      "ecosystem_specific": {
        "binaries": [
          {
            "python-ldb-dev": "2:1.1.24-1ubuntu3.2",
            "python-ldb": "2:1.1.24-1ubuntu3.2",
            "ldb-tools": "2:1.1.24-1ubuntu3.2",
            "python3-ldb": "2:1.1.24-1ubuntu3.2",
            "libldb-dev": "2:1.1.24-1ubuntu3.2",
            "libldb1": "2:1.1.24-1ubuntu3.2",
            "python3-ldb-dev": "2:1.1.24-1ubuntu3.2"
          }
        ],
        "availability": "No subscription needed"
      }
    }
  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://ubuntu.com/security/notices/USN-4888-1"
    },
    {
      "type": "REPORT",
      "url": "https://ubuntu.com/security/CVE-2020-27840"
    },
    {
      "type": "REPORT",
      "url": "https://ubuntu.com/security/CVE-2021-20277"
    }
  ]
}