{
  "schema_version": "1.7.0",
  "id": "USN-4715-1",
  "summary": "python-django vulnerability",
  "details": "Wang Baohua discovered that Django incorrectly extracted archive files. A\nremote attacker could possibly use this issue to extract files outside of\ntheir expected location.\n",
  "aliases": [],
  "upstream": [
    "UBUNTU-CVE-2021-3281"
  ],
  "related": [],
  "published": "2021-02-01T11:55:47.444263Z",
  "modified": "2025-09-25T09:35:33Z",
  "affected": [
    {
      "package": {
        "ecosystem": "Ubuntu:16.04:LTS",
        "name": "python-django",
        "purl": "pkg:deb/ubuntu/python-django@1.8.7-1ubuntu5.14?arch=source&distro=xenial"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "1.8.7-1ubuntu5.14"
            }
          ]
        }
      ],
      "versions": [
        "1.7.9-1ubuntu5",
        "1.8.5-2ubuntu1",
        "1.8.7-1ubuntu1",
        "1.8.7-1ubuntu2",
        "1.8.7-1ubuntu3",
        "1.8.7-1ubuntu4",
        "1.8.7-1ubuntu5",
        "1.8.7-1ubuntu5.1",
        "1.8.7-1ubuntu5.2",
        "1.8.7-1ubuntu5.4",
        "1.8.7-1ubuntu5.5",
        "1.8.7-1ubuntu5.6",
        "1.8.7-1ubuntu5.7",
        "1.8.7-1ubuntu5.8",
        "1.8.7-1ubuntu5.9",
        "1.8.7-1ubuntu5.10",
        "1.8.7-1ubuntu5.11",
        "1.8.7-1ubuntu5.12",
        "1.8.7-1ubuntu5.13"
      ],
      "ecosystem_specific": {
        "binaries": [
          {
            "binary_name": "python-django",
            "binary_version": "1.8.7-1ubuntu5.14"
          },
          {
            "binary_name": "python-django-common",
            "binary_version": "1.8.7-1ubuntu5.14"
          },
          {
            "binary_name": "python3-django",
            "binary_version": "1.8.7-1ubuntu5.14"
          }
        ],
        "availability": "No subscription required"
      },
      "database_specific": {
        "cves_map": {
          "ecosystem": "Ubuntu:16.04:LTS",
          "cves": [
            {
              "id": "CVE-2021-3281",
              "severity": [
                {
                  "type": "CVSS_V3",
                  "score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:L/A:N"
                },
                {
                  "type": "Ubuntu",
                  "score": "medium"
                }
              ]
            }
          ]
        }
      }
    },
    {
      "package": {
        "ecosystem": "Ubuntu:18.04:LTS",
        "name": "python-django",
        "purl": "pkg:deb/ubuntu/python-django@1:1.11.11-1ubuntu1.10?arch=source&distro=bionic"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "1:1.11.11-1ubuntu1.10"
            }
          ]
        }
      ],
      "versions": [
        "1:1.11.4-1ubuntu1",
        "1:1.11.6-1ubuntu1",
        "1:1.11.9-1ubuntu1",
        "1:1.11.11-1ubuntu1",
        "1:1.11.11-1ubuntu1.1",
        "1:1.11.11-1ubuntu1.2",
        "1:1.11.11-1ubuntu1.3",
        "1:1.11.11-1ubuntu1.4",
        "1:1.11.11-1ubuntu1.5",
        "1:1.11.11-1ubuntu1.6",
        "1:1.11.11-1ubuntu1.7",
        "1:1.11.11-1ubuntu1.8",
        "1:1.11.11-1ubuntu1.9"
      ],
      "ecosystem_specific": {
        "binaries": [
          {
            "binary_name": "python-django",
            "binary_version": "1:1.11.11-1ubuntu1.10"
          },
          {
            "binary_name": "python-django-common",
            "binary_version": "1:1.11.11-1ubuntu1.10"
          },
          {
            "binary_name": "python3-django",
            "binary_version": "1:1.11.11-1ubuntu1.10"
          }
        ],
        "availability": "No subscription required"
      },
      "database_specific": {
        "cves_map": {
          "ecosystem": "Ubuntu:18.04:LTS",
          "cves": [
            {
              "id": "CVE-2021-3281",
              "severity": [
                {
                  "type": "CVSS_V3",
                  "score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:L/A:N"
                },
                {
                  "type": "Ubuntu",
                  "score": "medium"
                }
              ]
            }
          ]
        }
      }
    },
    {
      "package": {
        "ecosystem": "Ubuntu:20.04:LTS",
        "name": "python-django",
        "purl": "pkg:deb/ubuntu/python-django@2:2.2.12-1ubuntu0.3?arch=source&distro=focal"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "2:2.2.12-1ubuntu0.3"
            }
          ]
        }
      ],
      "versions": [
        "1:1.11.22-1ubuntu1",
        "2:2.2.6-1ubuntu1",
        "2:2.2.9-2ubuntu1",
        "2:2.2.10-1",
        "2:2.2.10-1ubuntu1",
        "2:2.2.11-1",
        "2:2.2.12-1",
        "2:2.2.12-1ubuntu0.1",
        "2:2.2.12-1ubuntu0.2"
      ],
      "ecosystem_specific": {
        "binaries": [
          {
            "binary_name": "python3-django",
            "binary_version": "2:2.2.12-1ubuntu0.3"
          }
        ],
        "availability": "No subscription required"
      },
      "database_specific": {
        "cves_map": {
          "ecosystem": "Ubuntu:20.04:LTS",
          "cves": [
            {
              "id": "CVE-2021-3281",
              "severity": [
                {
                  "type": "CVSS_V3",
                  "score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:L/A:N"
                },
                {
                  "type": "Ubuntu",
                  "score": "medium"
                }
              ]
            }
          ]
        }
      }
    }
  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://ubuntu.com/security/notices/USN-4715-1"
    },
    {
      "type": "REPORT",
      "url": "https://ubuntu.com/security/CVE-2021-3281"
    }
  ]
}